2018-12-09 19:48:43,854 - __main__ - INFO - Start print log
2018-12-09 19:48:43,854 - __main__ - WARNING - Something maybe fail.
2018-12-09 19:48:43,855 - __main__ - INFO - Finish
2018-12-10 09:23:46,272-__main__-INFO-Start print log
2018-12-10 09:23:46,279-__main__-WARNING-Something maybe fail!
2018-12-10 09:23:46,279-__main__-ERROR-Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "D:/python_script/3-11   3-33/xml_read/TEST.py", line 20, in <module>
    open("sklearn.txt",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2018-12-10 09:23:46,280-__main__-INFO-Finish
2018-12-10 09:24:28,737-__main__-INFO-Start print log
2018-12-10 09:24:28,737-__main__-WARNING-Something maybe fail!
2018-12-10 09:24:28,738-__main__-INFO-Finish
2018-12-10 09:26:14,645-__main__-INFO-Start print log
2018-12-10 09:26:14,645-__main__-WARNING-Something maybe fail!
2018-12-10 09:26:14,645-__main__-ERROR-Faild to open sklearn.txt from logger.error
Traceback (most recent call last):
  File "D:/python_script/3-11   3-33/xml_read/TEST.py", line 20, in <module>
    open("sklearn.txt",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2018-12-10 09:26:14,646-__main__-INFO-Finish
2018-12-10 09:59:37,267-__main__-INFO-Start print info
2018-12-10 09:59:37,273-__main__-WARNING-warn
2018-12-10 09:59:37,273-__main__-ERROR-No such file or directory
Traceback (most recent call last):
  File "D:/python_script/3-11   3-33/xml_read/TEST.py", line 47, in <module>
    open("sklearn.txt",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2018-12-10 10:08:23,696-__main__-INFO-Start print info
2018-12-10 10:08:23,696-__main__-WARNING-something may be warn
2018-12-10 10:08:23,696-__main__-ERROR-No such file or diretory
Traceback (most recent call last):
  File "D:/python_script/3-11   3-33/xml_read/TEST.py", line 47, in <module>
    open("sklearn.txt",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2018-12-10 11:41:54,084-__main__-INFO-Start print info
2018-12-10 11:41:54,089-__main__-WARNING-something may be warn
2018-12-10 11:41:54,089-__main__-ERROR-No such file or diretory
Traceback (most recent call last):
  File "D:/python_script/3-11   3-33/xml_read/TEST.py", line 47, in <module>
    open("sklearn.txt",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
2018-12-10 13:23:26,767-__main__-INFO-Start print info
2018-12-10 13:23:26,773-__main__-WARNING-something may be warn
2018-12-10 13:23:26,774-__main__-ERROR-No such file or diretory
Traceback (most recent call last):
  File "D:/python_script/3-11   3-33/xml_read/TEST.py", line 47, in <module>
    open("sklearn.txt",'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'sklearn.txt'
